# Generated by Django 3.0.7 on 2020-06-08 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 20, 50, 27, 133175)),
        ),
    ]
