# Generated by Django 3.0.7 on 2020-06-08 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200608_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='slug',
            field=models.TextField(default='hello'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 22, 15, 42, 583265)),
        ),
    ]
