# Generated by Django 3.0.7 on 2020-06-08 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20200608_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 22, 21, 15, 707578)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=models.SlugField(),
        ),
    ]
