# Generated by Django 3.0.7 on 2020-06-08 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20200608_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 22, 27, 55, 976663)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
